---
# tasks file for mariadb
- name: Install 'mariadb-server' and 'MySQL-python' packages
  yum: 
    name: "{{ item }}" 
    update_cache: true
    state: latest
  loop:
    - mariadb-server
    - MySQL-python

- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create "{{ db_name }}" database from file
  mysql_db:
    name: "{{ db_name }}"
    state: present 

- name: Create database user "{{ db_user }}" 
  mysql_user:
    name: "{{ db_user }}" 
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL" 
    state: present
  no_log: true  